#!/usr/bin/env bash

env=$1
app="wealth"
region="us-east-1"

aws ecr create-repository --region $region --repository-name $app/$env/logout \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false

sleep 1s

aws ecr create-repository --region $region --repository-name $app/$env/ynab/login \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/token \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/get-budgets \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/get-accounts \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/get-monthly-net-worth \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/get-monthly-net-worth-for-account \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/ynab/get-daily-net-worth \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/forecast \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
   
sleep 1s


aws ecr create-repository --region $region --repository-name $app/$env/verify \
   --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=false
