#!/usr/bin/env bash
export AWS_PROFILE=personal
export AWS_REGION=us-east-1
export BUCKET_NAME=wealth-for-ynab-dev-websitebucket-1tkoe5kox44ps
export DISTRIBUTION_ID=E3ABQQEILQJACJ

api() {
    echo "Building and deploying API"

    sam build --cached --parallel

    sam deploy --config-env dev
}

web() {
    echo "Building and deploying website"
    cd web
    npm run build
    aws s3 sync --cache-control 'max-age=604800' --exclude index.html dist s3://$BUCKET_NAME
    aws s3 sync --cache-control 'no-cache' dist s3://$BUCKET_NAME
    aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION_ID --paths /*
}


[[ -z $1 || "$1" == "api" ]] && api

[[ -z $1 || "$1" == "web" ]] && web
