export const USER_FETCHED = 'USER_FETCHED';
export const ACCESS_TOKEN_FETCHED = 'ACCESS_TOKEN_FETCHED';
export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_COMPLETED_SUCCESS = 'AUTH_COMPLETED_SUCCESS';
export const AUTH_COMPLETED_FAIL = 'AUTH_COMPLETED_FAIL';