#!/usr/bin/env bash
export AWS_PROFILE=personal
sam build Forecast --parallel
# sam local invoke --event events/forecast.json Forecast
sam local invoke --event events/forecast_daily_365.json Forecast
